import { Inter } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/sideNav/Sidebar";
import Dashboard from "./dashboard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="row">
          {<Sidebar />}
          <div className="container">{children}</div>
        </div>
      </body>
    </html>
  );
}
