import { Inter } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/sideNav/Sidebar";
import Dashboard from "./dashboard/page";
import { Providers } from "./providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BiblioTechAI Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="row">
          <Providers>
            {<Sidebar />}
            <div className="container">{children}</div>
          </Providers>
        </div>
      </body>
    </html>
  );
}
