import { Inter } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/sideNav/Sidebar";
import Dashboard from "./dashboard/page";
import { Providers } from "./providers/providers";
import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BiblioTechAI Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <div className="row">
          <MantineProvider>
            <Providers>
              {<Sidebar />}
              <div className="container">{children}</div>
            </Providers>
          </MantineProvider>
        </div>
      </body>
    </html>
  );
}
